# Generated by Django 5.0.1 on 2024-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_enquirydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydb',
            name='Car_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
