# Generated by Django 5.0.1 on 2024-01-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_enquirydb_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
