# Generated by Django 5.0.1 on 2024-02-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_enquirydb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydb',
            name='Car_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
