# Generated by Django 5.0.1 on 2024-02-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='User_Id',
            new_name='Username',
        ),
    ]
