# Generated by Django 5.0.1 on 2024-02-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquirydb',
            old_name='Place',
            new_name='Offer',
        ),
    ]
