# Generated by Django 5.0.1 on 2024-02-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_enquirydb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydb',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
